pipeline:
  build:
    image: lins05/seadrive-builder:latest
    pull: true
    privileged: true
    secrets: [ bintray_auth, bintray_stable_repo, bintray_unstable_repo, slack_webhook ]
    commands:
      - ./scripts/drone-build.sh

  slack:
      image: plugins/slack
      channel: seafile-client
      secrets: [ slack_webhook ]
      username: drone
      when:
        branch: [lpad, lpad-dev]
        status: [ failure ]
